### ISSUE TITLE
Doesn't appear to be anything in the .pdf manual on RMX command

### ISSUE THREAD

**Issue by findjonmos** [Dirtywave/M8Firmware#13]
Been scratching my head trying to figure out how to get RMX working.

I have watched the youtube channel latest 3.0 but couldn't figure RMX out still...prob coz I am getting old :)

Went to check the manual and noticed there is nothing in there for RMX

**Comment by trash80** [comment]
Manual is still being updated for version 3 (sorry for the delay). RMX only works on tracks to the left of the RMX command itself. EG: put it on track 8 to affect tracks 1-7.

**Comment by findjonmos** [comment]
Cool, thanks for the update no worries for the delay just thought it might have been missed, but its all in hand :)

Just managed to get it all figured out and working, just was confused about how it works when you have multiple phrases but realised that the phrase where you put the RMX command is only controlling the same phrase in a different track rather than having any power to select different phrases to change. Just me being a bit slow to catch on :)

Thanks for all your efforts and the epic work you are doing. M8 is such a great device, I take it everywhere I go...my kids have Teddy Bears, I have the M8 lol

**Comment by findjonmos** [comment]
Closing as there is no issue, the changes to the manual are in the pipeline and will be released when its all ready
