### ISSUE TITLE
Faster save shortcut

### ISSUE THREAD

**Issue by khogeland** [Dirtywave/M8Firmware#15]
Hey, amazing device. Everything seems well thought out and intuitive.

One pain point, though, is having to navigate to the project page and then to the save button every time I want to save. Every other device I use has some split-second shortcut I can commit to muscle memory so I never have to interrupt what I'm doing and can save instinctively before trying anything potentially destructive.

I don't know if you have any unused shortcut combos left or if this exists and just isn't in the manual but if possible this would make the workflow much smoother.

**Comment by trash80** [comment]
Why do you need to save so often? You can perform a snapshot in the mixer screen by hitting shift+opt, and shift+edit will recall.

**Comment by khogeland** [comment]
That has the same problem, I need to navigate away from what I'm doing in order to save. Being able to save and recall quickly is a huge boon to creativity because you can experiment in the moment without worrying about ruining anything.

**Comment by trash80** [comment]
You navigate one page down (any screen mixer is down one to hit the shortcut)
