### ISSUE TITLE
Tempo on the side display is one less than project

### ISSUE THREAD

**Issue by KittenRaee** [Dirtywave/M8Firmware#4]
![image](https://user-images.githubusercontent.com/23376922/138576289-fe211f98-4fbb-443d-b71e-070ffe95bed1.png)
Tempo on side bar is displaying one less than on a project screen (picture taken via M8 Display for ease of screenshots)

**Comment by eeclarkjr** [comment]
Also reported by “kipptune” on the Discord server on 2/18/2022 however no firmware version was mentioned.  
![IMG_0123](https://user-images.githubusercontent.com/94812247/154831188-d7568fa8-3f4f-4955-8773-4ba03ec787d0.jpeg)
