### ISSUE TITLE
cannot upload new firmware `tcsetattr() failed`

### ISSUE THREAD

**Issue by koraysels** [Dirtywave/M8Firmware#8]
TyUpdater cannot upload the hex file. 

when I try to upload 2.5.0E. I'm on a macbook pro with big sur..

![image](https://user-images.githubusercontent.com/2418853/148111023-e6b677b8-835a-48f7-b94d-f0e112ab7678.png)

**Comment by trash80** [comment]
Try closing the remote display web app if you have that open. It sounds like it cannot open the serial port. This is not a firmware specific issue, more like a host / computer problem perhaps.

**Comment by koraysels** [comment]
tried using my hackintosh and it worked.. so probably software issue like you said. thaanks!!!!!
