### ISSUE TITLE
Issues with sample preview in sampler

### ISSUE THREAD

**Issue by koraysels** [Dirtywave/M8Firmware#9]
hi, not sure where I need to be to report issues with the firmware. 

 i'm on 2.7.5 

I'm having issues when previewing long samples in the sampler instrument. It repeats the first 500ms from the sample and then plays a short piece of the beginning of the sample. If I want to hear the rest of the sample I need to load it in the sample editor. 

is that a  glitch or is previewing long samples just not possible ? My first guess would be the SD card speed. I'm using the sd card that came with my m8 ... 

thanks for creating this wonderful device!

**Comment by db9979** [comment]
Best way is to commit it on discord. 

https://discord.gg/WEavjFNYHh

**Comment by koraysels** [comment]
cool, is there a issues channel ? or how does discord even work? it looks like slack bu tI can only see announcements and rules.....

**Comment by trash80** [comment]
Not sure if this is a bug or you are just triggering the sequencer before previewing a sample. Samples will preview in full if the sequencer is stopped before entering the browser, else it will replace and play the currently playing instrument from the sequencer. Also you are on old firmware, so check that.
